### ISSUE TITLE
Moveİn Process

### ISSUE THREAD

**Issue by kakalite94** [Infixo/CS2-RealPop#14]
Whem I'm installed last version of this mod no one moving in to city while i have lots of empty properties and workplaces. City happiness amount around 90. City populiton amount around 650k. İf i uninstall plugin issue is solving but i want to use this mod. İ tried the unistall the game and installed with last version of plugin but issue is continuing. Can you fix it please ?

**Comment by Infixo** [comment]
Can you please post Residential Data, Demographics and Workplace distribution from InfoLoom?

**Comment by kakalite94** [comment]
The increase in demographics occurred around the time I deleted the mode.
![1](https://github.com/Infixo/CS2-RealPop/assets/162797956/d91fef5d-e4b1-4165-b716-3636d46999b1)
![2](https://github.com/Infixo/CS2-RealPop/assets/162797956/db9eb1a4-e972-4e85-9d14-630cd058a848)
![3](https://github.com/Infixo/CS2-RealPop/assets/162797956/fc7d3d55-b649-440f-b216-4744eb478f4b)

**Comment by Infixo** [comment]
Residential Data looks ok, there is approx. 6% of empty properties, so limiter will allow new cims.
Hm. How can you tell that people are not moving in?

Your demographics looks super weird though. 0 dead people? How is that possible?

I can only say that pls. make sure you have v0.8.1 installed. Also, pls. post RealPop.cfg from BepInEx/config. Maybe it contains some old settings.

**Comment by kakalite94** [comment]
0 dead people causes from magical hearse mod they are actually dying but seems like that. everytime increasing empty properties but not decrasing and populiton is decrasing.
[RealPop.zip](https://github.com/Infixo/CS2-RealPop/files/14547582/RealPop.zip)

**Comment by Infixo** [comment]
This is the .dll, I asked for RealPop.cfg from BepInEx/config.
What is "magical hearse mod"? Can you give a link?

**Comment by Infixo** [comment]
Also, how can you tell that people are not moving in? Do you have 0 in "People Moving In" in Statistics?

**Comment by kakalite94** [comment]
> Also, how can you tell that people are not moving in? Do you have 0 in "People Moving In" in Statistics?

yes its amount only 250-300 people

> This is the .dll, I asked for RealPop.cfg from BepInEx/config.
What is "magical hearse mod"? Can you give a link?

[RealPop.zip](https://github.com/Infixo/CS2-RealPop/files/14547859/RealPop.zip)
https://thunderstore.io/c/cities-skylines-ii/p/Wayzware/Magical_Hearse/

**Comment by Infixo** [comment]
You have old values in the RealPop.cfg
```
## Treshold for free properties ratio to start spawning new households (in 1/1000); Vanilla has no restrictions, set to -1 to turn off
# Setting type: Int32
# Default value: 20
FreeRatioTreshold = 30

## Treshold for free properties ratio to spawn new households at full speed (in 1/1000); Vanilla has no restrictions
# Setting type: Int32
# Default value: 60
FreeRatioFullSpeed = 75
```
Change so they are the same as defaults (20 and 60).

**Comment by kakalite94** [comment]
it's completed. I wish you continued success. we are waiting action from you about garbage collection process. because we have issues about it. We have lots of garbage services but they don't collect garbage from some streets, and lots of garbage collector truck doesn't going to go collect wastes, we think it's stems from vanilla process. Thanks for help

**Comment by Infixo** [comment]
Ok, I am closing the issue then.
