### ISSUE TITLE
Elementary School time.

### ISSUE THREAD

**Issue by Samueras** [Infixo/CS2-RealPop#2]
Hey,
there is a bug in the Game that Children stay 2.5x longer in highschool than they should. That is the main reason you need so many elementary schools. I hoped to fix that with your mod, by decreasing those times. But sadly it doenst have a Setting for Elementary schools. Would it be possible to add that?

**Comment by Infixo** [comment]
1. Exactly how long do they stay in high-school in your case?
2. Please explain why do you think they stay "2.5x longer than they should".

**Comment by Infixo** [comment]
No response. Closing.
