### ISSUE TITLE
Rent of Low Residential Housing seems very low

### ISSUE THREAD

**Issue by jangoergens** [Infixo/CS2-RealPop#6]
My low residential homes have rents of 50/month which seems pretty low to me. Row housing or medium density housing is usually 10x as much and I think low residential housing in a good neighborhood should be at least 500/month.

**Comment by Infixo** [comment]
This has nothing to do with RealPop. Rent depends on Land Value, which depends on many factors, mainly level of buildings. Check out Land Value issue on forums.
