### ISSUE TITLE
Adjust Household spawning rate

### ISSUE THREAD

**Issue by Infixo** [Infixo/CS2-RealPop#8]
One of the reasons that new Adults are moving away is that there are no empty homes. They are taken by Outsiders. Because households spawn at crazy rate. Not going into details, the Household Demand is broken.
There should be some level of empty homes that blocks Outsiders, so new Adults have chance to find a new home.
Should be enough to actually use BuildingDemand... 100 means that there are hardly any empty properties, 0 means 10%, so quite a lot. But it calculated separately for 3 zones. Should have one.
What matters are actually only empty properties and homelessness - if big, then we don't need new households!
Formula: get empty properties, subtract from empty: homeless, and some minimum level of free (%), what remains is new Household Demad, the rest is the same.
Also, no need to run it 1024 per day...

**Comment by Infixo** [comment]
Implemented a limiter for new households in b61a232a536e20249854ae3f04a6356084ae418f,

**Comment by Thelic38** [comment]
This has also fixed the homeless issue.

**Comment by Infixo** [comment]
> This has also fixed the homeless issue.

Ha... interesting... could be some unexpected side-effect. Good :)

**Comment by Thelic38** [comment]
It gives people who are displaced by an residential demolition a better chance at finding a home.
