### ISSUE TITLE
Dogs

### ISSUE THREAD

**Issue by Thelic38** [Infixo/CS2-RealPop#9]
Can you control the number of dogs? There are households with over a dozen dogs in my cities. Its not adding to the simulation and it just looks odd. Not to mention its probably not doing great things for the framerate.

My %dogs per capita is ~30%. To put that in perspective, most European countries are between 5% and 20%.

**Comment by Thelic38** [comment]
![image](https://github.com/Infixo/CS2-RealPop/assets/152677602/e0edcbc9-bf93-43f6-9814-5e35aacf4fa9)
 Yvonne here has 14 dogs...leave some room on the sidewalk for others lady!

**Comment by Infixo** [comment]
I think this is actually a bug, most likely from patches that were supposed to "fix" dogs.
When a household is created, there is 20% chance to spawn a dog. Then it spawns 2nd with 10% chance and 3rd 10% chance. 
So it is really RARE than a household has 3 dogs - like 1:500. A household cannot have more than 3 dogs when it is created.

However, there also seceral places where dogs appear and disappear, like entering/exiting buildings, cars, trains, etc. I think there is a bug somewhere there that adds more dogs than removes.

I won't be able to fix it, it must be CO, and you should report this "12 dogs" issue. This is really absurd situation.

**Comment by Thelic38** [comment]
Ah ok, I wasn't sure if they were counted in family members or not. Kind of interesting that the walking formation just happens to work lol.

**Comment by Infixo** [comment]
Dogs are Pets and there is a separate logic for them. They are not counted as household members in features that RealPop is using.
I won't be fixing this, so I am closing the issue.
